name: braille_dart
description: A helper library for TUIs related to the Braille Unicode symbols.
version: 1.0.0
repository: https://github.com/boodywinreal/braille.dart

environment:
  sdk: ^3.0.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
